services:
  cao:
    image: 'oxodao/cardsagainstoverflow:latest'
    restart: 'unless-stopped'
    environment:
      - DB_USERNAME=cao
      - DB_PASSWORD=cao
      - DB_DATABASE=cao
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - '127.0.0.1:8000:8000'

  database:
    image: 'postgres:alpine'
    restart: 'unless-stopped'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=cao
      - POSTGRES_PASSWORD=cao
      - POSTGRES_DB=cao
    volumes:
      - './data:/var/lib/postgresql/data'

  grafana:
    image: 'grafana/grafana'
    restart: 'unless-stopped'
    volumes:
      - 'grafana:/var/lib/grafana'
    ports:
      - '127.0.0.1:3000:3000'

volumes:
  grafana: