version: "3.8"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080

  database:
    image: postgres:alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=cao
      - POSTGRES_PASSWORD=cao
      - POSTGRES_DB=cao
    volumes:
      - /opt/cao/data/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  grafana: