version: "3.8"
services:
  cao:
    image: oxodao/cardsagainstoverflow:latest
    restart: always
    environment:
      - DB_USERNAME=cao
      - DB_PASSWORD=cao
      - DB_DATABASE=cao
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - 8000:8000

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8001:8080

  database:
    image: postgres:alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=cao
      - POSTGRES_PASSWORD=cao
      - POSTGRES_DB=cao
    volumes:
      - ./data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana: