
DROP TABLE CARD_DECK;
DROP TABLE CARD;
DROP TABLE DECK;

CREATE TABLE DECK (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR
);

CREATE TABLE CARD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEXT VARCHAR,
    IS_BLACK_CARD INTEGER
);

CREATE TABLE CARD_DECK (
    CARD_ID INTEGER,
    DECK_ID INTEGER,
    PRIMARY KEY (CARD, DECK),
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID),
    FOREIGN KEY(DECK_ID) REFERENCES DECK(ID)
);