DROP FUNCTION IF EXISTS INSERT_DECK(DECK_TITLE VARCHAR, IS_SELECTED_BY_DEFAULT BOOL, BLACK_CARDS TEXT[], WHITE_CARDS TEXT[]);
DROP TABLE IF EXISTS STAT_DRAWN_CARD;
DROP TABLE IF EXISTS STAT_DRAWN_BLACK_CARD;
DROP TABLE IF EXISTS STAT_GAME;
DROP TABLE IF EXISTS CARD_DECK;
DROP TABLE IF EXISTS CARD;
DROP TABLE IF EXISTS DECK;

CREATE TABLE DECK
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR,
    AMT_BLACK INTEGER,
    AMT_WHITE INTEGER,
    SELECTED_BY_DEFAULT BOOL NOT NULL DEFAULT FALSE
);

CREATE TABLE CARD
(
    ID            SERIAL PRIMARY KEY,
    TEXT          VARCHAR,
    IS_BLACK_CARD BOOL NOT NULL DEFAULT FALSE
);

CREATE TABLE CARD_DECK
(
    CARD_ID INTEGER,
    DECK_ID INTEGER,
    PRIMARY KEY (CARD_ID, DECK_ID),
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID),
    FOREIGN KEY (DECK_ID) REFERENCES DECK (ID)
);

CREATE TABLE STAT_GAME
(
    ID   SERIAL PRIMARY KEY,
    DATE TIMESTAMP DEFAULT NOW(),
    IS_ZEN_MODE BOOL DEFAULT FALSE,
    AMT_TURNS INTEGER DEFAULT 0
);

CREATE TABLE STAT_DRAWN_CARD
(
    ID SERIAL PRIMARY KEY,
    GAME INTEGER,
    PICKED_CARD INTEGER,
    FOREIGN KEY (GAME) REFERENCES STAT_GAME(ID),
    FOREIGN KEY (PICKED_CARD) REFERENCES CARD(ID)
);

CREATE TABLE STAT_DRAWN_BLACK_CARD
(
    ID SERIAL PRIMARY KEY,
    GAME INTEGER,
    PICKED_CARD INTEGER,
    FOREIGN KEY (GAME) REFERENCES STAT_GAME(ID),
    FOREIGN KEY (PICKED_CARD) REFERENCES CARD(ID)
);

CREATE FUNCTION INSERT_DECK(DECK_TITLE VARCHAR, IS_SELECTED_BY_DEFAULT BOOL, BLACK_CARDS TEXT[], WHITE_CARDS TEXT[]) RETURNS void AS
$$
DECLARE
    DECLARE TMP_DECK_ID    INTEGER;
    DECLARE TMP_TEXT       VARCHAR;
    DECLARE TMP_CARD       INTEGER;
BEGIN
    INSERT INTO DECK(NAME, SELECTED_BY_DEFAULT, AMT_BLACK, AMT_WHITE)
    VALUES (DECK_TITLE, IS_SELECTED_BY_DEFAULT, array_length(BLACK_CARDS, 1), array_length(WHITE_CARDS, 1))
    RETURNING ID INTO TMP_DECK_ID;

    FOREACH TMP_TEXT IN ARRAY BLACK_CARDS
        LOOP
            INSERT INTO CARD(text, is_black_card) VALUES (TMP_TEXT, true) RETURNING ID INTO TMP_CARD;
            INSERT INTO CARD_DECK(CARD_ID, DECK_ID) VALUES (TMP_CARD, TMP_DECK_ID);
        END LOOP;

    FOREACH TMP_TEXT IN ARRAY WHITE_CARDS
        LOOP
            INSERT INTO CARD(text, is_black_card) VALUES (TMP_TEXT, false) RETURNING ID INTO TMP_CARD;
            INSERT INTO CARD_DECK(CARD_ID, DECK_ID) VALUES (TMP_CARD, TMP_DECK_ID);
        END LOOP;

END
$$ LANGUAGE plpgsql;