name: Docker Image CI

on:
  watch: 
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }} 
        repository: oxodao/cardsagainstoverflow
        tags: latest
        buildoptions: "--compress --force-rm"
